import psycopg2
import csv
from datetime import datetime

con = psycopg2.connect(
    database = "salesite",
    user = "adminsite",
    password = "zerokrunar",
    host = "127.0.0.1",
    port = "5432"
)

cur = con.cursor()

with open('data.csv') as file:
    reader = csv.reader(file, delimiter=';')
    for row in reader:
        sql = """INSERT INTO SALES (NAME,PRICE_OLD,PRICE_NEW,LINK,IMAGE_LINK,DATE_SALE)
            VALUES ('{name}','{price_old}','{price_new}','{link}','{image_link}','{date_sale}')""".format(name=row[0],price_old=row[2],price_new=row[1],link=row[4],image_link=row[3],date_sale=str(datetime.now().date()))
        cur.execute(sql)

# cur.execute('''CREATE TABLE SALES
#     (ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#     NAME TEXT NOT NULL,
#     PRICE_OLD REAL NOT NULL,
#     PRICE_NEW REAL NOT NULL,
#     LINK TEXT NOT NULL,
#     IMAGE_LINK TEXT NOT NULL,
#     DATE_SALE DATE NOT NULL);''')

# cur.execute(
#     "INSERT INTO STUDENT (ADMISSION,NAME,AGE,COURSE,DEPARTMENT) VALUES (3420,'John','18','Computer science','ICT')"
# )
# cur.execute(
#   "INSERT INTO STUDENT (ADMISSION,NAME,AGE,COURSE,DEPARTMENT) VALUES (3421, 'Joel', 17, 'Computer Science', 'ICT')"
# )
# cur.execute(
#   "INSERT INTO STUDENT (ADMISSION,NAME,AGE,COURSE,DEPARTMENT) VALUES (3422, 'Antony', 19, 'Electrical Engineering', 'Engineering')"
# )
# cur.execute(
#   "INSERT INTO STUDENT (ADMISSION,NAME,AGE,COURSE,DEPARTMENT) VALUES (3423, 'Alice', 18, 'Information Technology', 'ICT')"
# )

# print('Table create successfully')

# con.commit()
# print('Recorded successfully')

#
# cur.execute("DELETE from STUDENT where ADMISSION=3420;")
# con.commit()
# print("Total deleted rows:", cur.rowcount)
#
# cur.execute("SELECT ADMISSION, NAME, AGE, COURSE, DEPARTMENT from STUDENT")
#
# rows = cur.fetchall()
# for row in rows:
#     print("ADMISSION=", row[0])
#     print("NAME=", row[1])
#     print("AGE", row[2])
#     print("COURSE=", row[3])
#     print("DEPARTMENT=", row[4],"\n")
#
con.commit()
print("Operation successfully")
con.close()
