# Generated by Django 2.2.7 on 2019-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price_old', models.FloatField()),
                ('price_new', models.FloatField()),
                ('link', models.TextField()),
                ('image_link', models.TextField()),
                ('date_sale', models.DateField()),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
